package com.adam9e96.JunitStudy.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Hibernate가 생성하는 DDL
 * <p>
 * <code>
 * Hibernate:
 * create table member (
 * id bigint generated by default as identity,
 * name varchar(255) not null,
 * primary key (id)
 * )
 * </code>
 * </p>
 */
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Entity
@Data
@Builder
public class Member {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false)
    private Long id;
    @Column(name = "name", nullable = false)
    private String name;

}
